const canvas=document.querySelector('#particles'),ctx=canvas.getContext('2d');let view='status',phase='solid',material='neon',temp=22,pressure=1,volume=100,running=true,particles=[],drag=null,forceMode='attract',a1={x:72,y:75},a2={x:270,y:75};const colors={neon:'#28e5ed',argon:'#ffa1a5',oxygen:'#ff5d0c',water:'#fff'};const $=s=>document.querySelector(s);const settings={solid:[130,.15],liquid:[110,.65],gas:[75,1.25]};
function makeParticles(){const [n]=settings[phase];particles=Array.from({length:n},(_,i)=>{let p={x:15+Math.random()*330,y:15+Math.random()*390,vx:(Math.random()-.5)*2,vy:(Math.random()-.5)*2,r:phase==='gas'?4:6};if(phase==='solid'){p.x=48+(i%10)*27;p.y=285+Math.floor(i/10)*18;p.vx=p.vy=0}return p})}
function phaseForTemp(){const next=temp<30?'solid':temp<70?'liquid':'gas';if(next!==phase){phase=next;document.querySelectorAll('.phase').forEach(b=>b.classList.toggle('active',b.dataset.phase===phase));makeParticles()}}
function updateUI(){ $('#temp').textContent=Math.round(temp)+' K';$('#thermoFill').style.height=Math.min(100,20+temp*.65)+'%';$('#bucketLevel').style.width=Math.max(10,Math.min(100,(temp/120)*100))+'%';$('#pressureText').textContent='Áp suất '+pressure.toFixed(1)+' atm';$('#distanceText').textContent=(Math.abs(a2.x-a1.x)/90).toFixed(1)+' σ';$('#forceText').textContent=forceMode==='attract'?'Hút':'Đẩy';$('#gaugeNeedle').style.transform=`rotate(${-45+(pressure-1)*35}deg)`;drawGraph()}
function drawParticles(){ctx.clearRect(0,0,360,420);ctx.shadowBlur=10;ctx.shadowColor=colors[material];const scale=volume/100;particles.forEach(p=>{if(running){if(phase==='solid'){p.x+=Math.sin(Date.now()/200+p.y)*.1;p.y+=Math.cos(Date.now()/180+p.x)*.1}else{const speed=settings[phase][1]*(.5+temp/60)*(pressure/1.5);p.vx+=(Math.random()-.5)*.1;p.vy+=(Math.random()-.5)*.1;p.x+=p.vx*speed;p.y+=p.vy*speed;if(p.x<10||p.x>350)p.vx*=-1;if(p.y<10||p.y>410*scale)p.vy*=-1;p.x=Math.max(10,Math.min(350,p.x));p.y=Math.max(10,Math.min(410*scale,p.y))}}ctx.beginPath();ctx.fillStyle=colors[material];ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});ctx.shadowBlur=0}
function drawGraph(){const g=$('#graph'),c=g.getContext('2d');c.clearRect(0,0,230,145);c.strokeStyle='#aaa';c.beginPath();c.moveTo(25,10);c.lineTo(25,125);c.lineTo(220,125);c.stroke();c.fillStyle='#ddd';c.fillText('Thế năng',28,18);c.fillText('Khoảng cách',145,141);c.strokeStyle='#f33';c.lineWidth=3;c.beginPath();for(let x=25;x<220;x++){const r=(x-25)/45+.45;const y=forceMode==='attract'?90-55*(Math.exp(-r)/r):90+35*Math.exp(-r)/r;c.lineTo(x,y)}c.stroke();c.fillStyle='#f6d16f';c.beginPath();c.arc(25+Math.abs(a2.x-a1.x)/2,90,5,0,7);c.fill()}
function setView(next){view=next;['status','phase','interaction'].forEach(v=>{$('#'+v+'Panel').classList.toggle('hidden',v!==next)});document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===next));}
function pointerStart(type,e){e.preventDefault();const p=e.touches?e.touches[0]:e;drag={type,x:p.clientX,y:p.clientY}}
function pointerMove(e){if(!drag)return;const p=e.touches?e.touches[0]:e,dy=p.clientY-drag.y;if(drag.type==='bucket'){temp=Math.max(5,Math.min(120,temp-dy*.35));phaseForTemp();updateUI()}if(drag.type==='lid'){volume=Math.max(55,Math.min(125,volume-dy*.35));$('#lid').style.top=(2+(100-volume)*.8)+'px';drag.y=p.clientY;updateUI()}if(drag.type==='pump'){pressure=Math.max(.2,Math.min(3,pressure+dy*.008));drag.y=p.clientY;updateUI()}if(drag.type==='atom'){const r=canvas.getBoundingClientRect(),x=(p.clientX-r.left)*360/r.width,y=(p.clientY-r.top)*420/r.height;a2={x,y};updateUI()}}
function end(){drag=null}
$('#bucket').addEventListener('pointerdown',e=>pointerStart('bucket',e));$('#lid').addEventListener('pointerdown',e=>pointerStart('lid',e));$('#pumpHandle').addEventListener('pointerdown',e=>pointerStart('pump',e));canvas.addEventListener('pointerdown',e=>{if(view!=='interaction')return;pointerStart('atom',e)});window.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',end);window.addEventListener('pointercancel',end);
document.querySelectorAll('.material').forEach(b=>b.onclick=()=>{material=b.dataset.material;document.querySelectorAll('.material').forEach(x=>x.classList.toggle('active',x===b))});document.querySelectorAll('.phase').forEach(b=>b.onclick=()=>{phase=b.dataset.phase;temp=phase==='solid'?22:phase==='liquid'?45:85;makeParticles();updateUI()});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll('[data-force]').forEach(b=>b.onclick=()=>{forceMode=b.dataset.force;document.querySelectorAll('[data-force]').forEach(x=>x.classList.toggle('active',x===b));updateUI()});$('#pause').onclick=()=>running=false;$('#play').onclick=()=>running=true;$('#reset').onclick=()=>{temp=22;pressure=1;volume=100;phase='solid';setView('status');makeParticles();updateUI()};makeParticles();updateUI();setView('status');setInterval(drawParticles,30);