/* Mission animation + generated SFX layer. No external audio files are required. */
const FX={ctx:null,master:null,ambient:null,raf:0,parts:[],pulse:0,flash:0,shake:0,active:false};
function audio(){if(FX.ctx)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;FX.ctx=new AC();FX.master=FX.ctx.createGain();FX.master.gain.value=.12;FX.master.connect(FX.ctx.destination)}
function tone(freq,duration=.12,type='sine',gain=.08,slide=0){audio();if(!FX.ctx)return;const o=FX.ctx.createOscillator(),g=FX.ctx.createGain(),t=FX.ctx.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.linearRampToValueAtTime(Math.max(30,freq+slide),t+duration);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(gain,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(FX.master);o.start(t);o.stop(t+duration+.02)}
function sfx(name){audio();if(!FX.ctx)return; if(FX.ctx.state==='suspended')FX.ctx.resume(); if(name==='walk')tone(90,.045,'square',.025,-18);if(name==='ui')tone(520,.08,'triangle',.05,140);if(name==='pump'){tone(110,.16,'square',.07,80);setTimeout(()=>tone(62,.1,'sawtooth',.04,-20),70)}if(name==='weld'){tone(180,.25,'sawtooth',.05,260);tone(900,.08,'square',.018,-300)}if(name==='cool'){tone(330,.5,'sine',.04,-170)}if(name==='success'){tone(440,.12,'triangle',.06,120);setTimeout(()=>tone(660,.2,'triangle',.06,180),100)}if(name==='fail'){tone(180,.35,'sawtooth',.08,-130);setTimeout(()=>tone(90,.4,'square',.05,-30),130)}}
function fxBurst(x,y,color='#55e6e0',count=14){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=1+Math.random()*3;FX.parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,color})}}
function fxCanvas(){const c=document.querySelector('#fx');if(!c)return;const q=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;q.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);q.clearRect(0,0,c.clientWidth,c.clientHeight);FX.parts=FX.parts.filter(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.08;p.life-=.025;q.globalAlpha=Math.max(0,p.life);q.fillStyle=p.color;q.fillRect(p.x,p.y,3,3);return p.life>0});q.globalAlpha=1;if(FX.flash>0){q.fillStyle=`rgba(255,100,90,${FX.flash})`;q.fillRect(0,0,c.clientWidth,c.clientHeight);FX.flash-=.035}requestAnimationFrame(fxCanvas)}
function missionFx(kind){const canvas=document.querySelector('#world'),overlay=document.querySelector('#fx');if(!canvas||!overlay)return;const r=canvas.getBoundingClientRect(),scaleX=canvas.clientWidth/900,scaleY=canvas.clientHeight/540;let x=450,y=270;color='#55e6e0';if(kind==='weld'){x=180;y=405;color='#ffb84d'}if(kind==='pressure'){x=145;y=135;color='#ff5959'}if(kind==='pump'){x=735;y=135;color='#5fe6d2'}if(kind==='core'){x=440;y=405;color='#b38cff'}fxBurst(x*scaleX,y*scaleY,color,kind==='weld'?24:16);FX.flash=kind==='fail'?.18:.0;overlay.classList.add('fx-pulse');setTimeout(()=>overlay.classList.remove('fx-pulse'),280)}
/* Sounds are triggered by real interaction, not automatic background audio. */
document.addEventListener('pointerdown',e=>{audio();const id=e.target.id||'';if(id==='pump')sfx('pump');if(e.target.classList.contains('weld'))sfx('weld');if(e.target.classList.contains('action-btn'))sfx('ui')},{passive:true});document.addEventListener('keydown',e=>{if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)&&window.player?.moving)sfx('walk')},{passive:true});
window.addEventListener('load',()=>{const c=document.querySelector('#fx');if(c)fxCanvas()});
